name: PR

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24", "1.23"]
        directory: ["./v3"]
    name: Go ${{ matrix.go }}.x PR Validate ${{ matrix.directory }} (Modules)
    
    services:
      389ds:
        image: quay.io/389ds/dirsrv:latest
        ports:
          - 3389:3389
          - 3636:3636
        env:
          DS_DM_PASSWORD: admin123
          DS_SUFFIX_NAME: dc=example,dc=com 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install LDAP utilities
        run: |
          sudo apt-get update
          sudo apt-get install -yqq ldap-utils netcat-openbsd

      - name: Wait for 389 Directory Server
        run: |
          echo "Waiting for 389 DS port to be available..."
          timeout 30 bash -c 'until nc -z localhost 3389; do echo "Waiting for port 3389..."; sleep 2; done'
          echo "Port 3389 is open, waiting a bit more for LDAP service..."
          sleep 10

      - name: Provision LDAP with dummy data
        run: |
          # Create organizational units
          cat << EOF | ldapadd -x -H ldap://localhost:3389 -D "cn=Directory Manager" -w admin123
          dn: ou=people,dc=example,dc=com
          objectClass: organizationalUnit
          ou: people
          
          dn: ou=groups,dc=example,dc=com
          objectClass: organizationalUnit
          ou: groups
          EOF

          # Add dummy users
          cat << EOF | ldapadd -x -H ldap://localhost:3389 -D "cn=Directory Manager" -w admin123
          dn: cn=John Doe,ou=people,dc=example,dc=com
          objectClass: inetOrgPerson
          objectClass: organizationalPerson
          objectClass: person
          objectClass: top
          cn: John Doe
          sn: Doe
          givenName: John
          mail: john.doe@example.com
          uid: jdoe
          userPassword: password123
          
          dn: cn=Jane Smith,ou=people,dc=example,dc=com
          objectClass: inetOrgPerson
          objectClass: organizationalPerson
          objectClass: person
          objectClass: top
          cn: Jane Smith
          sn: Smith
          givenName: Jane
          mail: jane.smith@example.com
          uid: jsmith
          userPassword: password456
          
          dn: cn=Bob Wilson,ou=people,dc=example,dc=com
          objectClass: inetOrgPerson
          objectClass: organizationalPerson
          objectClass: person
          objectClass: top
          cn: Bob Wilson
          sn: Wilson
          givenName: Bob
          mail: bob.wilson@example.com
          uid: bwilson
          userPassword: password789
          EOF

          # Add dummy groups
          cat << EOF | ldapadd -x -H ldap://localhost:3389 -D "cn=Directory Manager" -w admin123
          dn: cn=developers,ou=groups,dc=example,dc=com
          objectClass: groupOfNames
          cn: developers
          description: Development team
          member: cn=John Doe,ou=people,dc=example,dc=com
          member: cn=Jane Smith,ou=people,dc=example,dc=com
          
          dn: cn=admins,ou=groups,dc=example,dc=com
          objectClass: groupOfNames
          cn: admins
          description: System administrators
          member: cn=Bob Wilson,ou=people,dc=example,dc=com
          EOF

      - name: Verify LDAP data
        run: |
          echo "Verifying LDAP entries..."
          ldapsearch -x -H ldap://localhost:3389 -D "cn=Directory Manager" -w admin123 -b "dc=example,dc=com" "(objectClass=*)" dn
          echo "Total entries:"
          ldapsearch -x -H ldap://localhost:3389 -D "cn=Directory Manager" -w admin123 -b "dc=example,dc=com" "(objectClass=*)" dn | grep -c "^dn:"

      - name: Set LDAP environment variables
        run: |
          echo "LDAP_HOST=localhost" >> $GITHUB_ENV
          echo "LDAP_PORT=3389" >> $GITHUB_ENV
          echo "LDAP_BIND_DN=cn=Directory Manager" >> $GITHUB_ENV
          echo "LDAP_BIND_PASSWORD=admin123" >> $GITHUB_ENV
          echo "LDAP_BASE_DN=dc=example,dc=com" >> $GITHUB_ENV

      - name: Version
        run: go version
